import {
  CANVAS_EDITOR_BASE_FIELD,
  CANVAS_EDITOR_STYLE_FIELD,
  CHART_EDITOR_BASE_FIELD,
  CHART_EDITOR_STYLE_FIELD,
  CONTROL_EDITOR_BASE_FIELD,
  CONTROL_EDITOR_STYLE_FIELD,
  TABLE_EDITOR_BASE_FIELD,
  TABLE_EDITOR_STYLE_FIELD,
  TEXT_EDITOR_BASE_FIELD,
  TEXT_EDITOR_STYLE_FIELD
} from '../fields';
import { mainTypes } from '../../types';
import { EditorBaseField } from '../../interfaces';


export const EDITOR_BASE_FIELDS: Record<mainTypes, EditorBaseField[]> = {
  canvas: [CANVAS_EDITOR_BASE_FIELD, CANVAS_EDITOR_STYLE_FIELD],
  chart: [CHART_EDITOR_BASE_FIELD, CHART_EDITOR_STYLE_FIELD],
  table: [TABLE_EDITOR_BASE_FIELD, TABLE_EDITOR_STYLE_FIELD],
  text: [TEXT_EDITOR_BASE_FIELD, TEXT_EDITOR_STYLE_FIELD],
  control: [CONTROL_EDITOR_BASE_FIELD, CONTROL_EDITOR_STYLE_FIELD]
};
