import { ChartTypesEnum } from '../enums';

export const CHART_DEFAULT_MOCKS_MAP: Partial<{ [key in ChartTypesEnum]: string[] }> = {
	[ChartTypesEnum.line]: ['barAndLineData'],
	[ChartTypesEnum.bar]: ['barAndLineData'],
	[ChartTypesEnum.combination]: ['barAndLineData'],
	[ChartTypesEnum.area]: ['areaChartData'],
	[ChartTypesEnum.scatter]: ['maleHeightWeight', 'femaleHeightWeight'],
	[ChartTypesEnum.bubble]: ['maleHeightWeight', 'femaleHeightWeight'],
	[ChartTypesEnum.pie]: ['pieChartData'],
	[ChartTypesEnum.donut]: ['donutChartData'],
	[ChartTypesEnum.boxPlot]: ['boxPlotData'],
	[ChartTypesEnum.candlestick]: ['candlestickAndOhlcData'],
	[ChartTypesEnum.ohlc]: ['candlestickAndOhlcData'],
	[ChartTypesEnum.heatmap]: ['heatmapData'],
	[ChartTypesEnum.histogram]: ['histogramData'],
	[ChartTypesEnum.nightingale]: ['doubleGroupData'],
	[ChartTypesEnum.radialColumn]: ['doubleGroupData'],
	[ChartTypesEnum.radarArea]: ['radarAreaData'],
	[ChartTypesEnum.radarLine]: ['radarLineData'],
	[ChartTypesEnum.radialBar]: ['radialBarData'],
	[ChartTypesEnum.rangeArea]: ['rangeAreaData'],
	[ChartTypesEnum.rangeBar]: ['rangeBarData'],
	[ChartTypesEnum.waterfall]: ['waterfallData'],
	[ChartTypesEnum.sunburst]: ['sunburstData'],
	[ChartTypesEnum.treemap]: ['treemapData'],
	[ChartTypesEnum.sankey]: ['sankeyData'],
	[ChartTypesEnum.chord]: ['chordData'],
	[ChartTypesEnum.coneFunnel]: ['coneFunnelData'],
	[ChartTypesEnum.funnel]: ['funnelData'],
	[ChartTypesEnum.pyramid]: ['funnelData'],
};
