import { ChartTypesEnum } from '../enums';
import {
  CHART_TITLE,
  CHART_LEGEND,
  CHART_X_AXIS,
  CHART_Y_AXIS,
  CHART_GRID,
  CHART_TOOLTIP,

  // series
  CHART_BAR_SERIES,
  CHART_LINE_SERIES,
  CHART_SCATTER_SERIES,
  CHART_PIE_SERIES,
  CHART_BOX_PLOT_SERIES,
  CHART_CANDLESTICK_SERIES,
  CHART_CHORD_SERIES,
  CHART_EFFECT_SCATTER_SERIES,
  CHART_FUNNEL_SERIES,
  CHART_GAUGE_SERIES,
  CHART_GRAPH_SERIES,
  CHART_HEATMAP_SERIES,
  CHART_LINES_SERIES,
  CHART_MAP_SERIES,
  CHART_PARALLEL_SERIES,
  CHART_PICTORIAL_BAR_SERIES,
  CHART_SANKEY_SERIES,
  CHART_SUNBURST_SERIES,
  CHART_THEME_RIVER_SERIES,
  CHART_TREE_SERIES,
  CHART_TREEMAP_SERIES,
  CHART_RADAR_SERIES,
} from './fields';
import { EditorChartField } from 'ngx-puzzle/core';

export const CHART_FIELDS_MAP: Record<ChartTypesEnum, EditorChartField[]> = {
  [ChartTypesEnum.bar]: [
    CHART_TITLE,  CHART_BAR_SERIES, CHART_LEGEND, CHART_X_AXIS, CHART_Y_AXIS, CHART_GRID, CHART_TOOLTIP,
  ],
  [ChartTypesEnum.line]: [
    CHART_TITLE,  CHART_LINE_SERIES, CHART_LEGEND, CHART_X_AXIS, CHART_Y_AXIS, CHART_GRID, CHART_TOOLTIP,
  ],
  [ChartTypesEnum.scatter]: [
    CHART_TITLE,  CHART_SCATTER_SERIES, CHART_LEGEND, CHART_X_AXIS, CHART_Y_AXIS, CHART_GRID, CHART_TOOLTIP,
  ],
  [ChartTypesEnum.pie]: [
    CHART_TITLE,  CHART_PIE_SERIES, CHART_LEGEND, CHART_X_AXIS, CHART_Y_AXIS, CHART_GRID, CHART_TOOLTIP,
  ],
  [ChartTypesEnum.boxPlot]: [
    CHART_TITLE,  CHART_BOX_PLOT_SERIES, CHART_LEGEND, CHART_X_AXIS, CHART_Y_AXIS, CHART_GRID, CHART_TOOLTIP,
  ],
  [ChartTypesEnum.candlestick]: [
    CHART_TITLE,  CHART_CANDLESTICK_SERIES, CHART_LEGEND, CHART_X_AXIS, CHART_Y_AXIS, CHART_GRID, CHART_TOOLTIP,
  ],
  [ChartTypesEnum.radar]: [
    CHART_TITLE,  CHART_RADAR_SERIES, CHART_LEGEND, CHART_X_AXIS, CHART_Y_AXIS, CHART_GRID, CHART_TOOLTIP,
  ],
  [ChartTypesEnum.chord]: [
    CHART_TITLE,  CHART_CHORD_SERIES, CHART_LEGEND, CHART_X_AXIS, CHART_Y_AXIS, CHART_GRID, CHART_TOOLTIP,
  ],
  [ChartTypesEnum.effectScatter]: [
    CHART_TITLE,  CHART_EFFECT_SCATTER_SERIES, CHART_LEGEND, CHART_X_AXIS, CHART_Y_AXIS, CHART_GRID, CHART_TOOLTIP,
  ],
  [ChartTypesEnum.funnel]: [
    CHART_TITLE,  CHART_FUNNEL_SERIES, CHART_LEGEND, CHART_X_AXIS, CHART_Y_AXIS, CHART_GRID, CHART_TOOLTIP,
  ],
  [ChartTypesEnum.gauge]: [
    CHART_TITLE,  CHART_GAUGE_SERIES, CHART_LEGEND, CHART_X_AXIS, CHART_Y_AXIS, CHART_GRID, CHART_TOOLTIP,
  ],
  [ChartTypesEnum.graph]: [
    CHART_TITLE,  CHART_GRAPH_SERIES, CHART_LEGEND, CHART_X_AXIS, CHART_Y_AXIS, CHART_GRID, CHART_TOOLTIP,
  ],
  [ChartTypesEnum.heatmap]: [
    CHART_TITLE,  CHART_HEATMAP_SERIES, CHART_LEGEND, CHART_X_AXIS, CHART_Y_AXIS, CHART_GRID, CHART_TOOLTIP,
  ],
  [ChartTypesEnum.lines]: [
    CHART_TITLE,  CHART_LINES_SERIES, CHART_LEGEND, CHART_X_AXIS, CHART_Y_AXIS, CHART_GRID, CHART_TOOLTIP,
  ],
  [ChartTypesEnum.map]: [
    CHART_TITLE,  CHART_MAP_SERIES, CHART_LEGEND, CHART_X_AXIS, CHART_Y_AXIS, CHART_GRID, CHART_TOOLTIP,
  ],
  [ChartTypesEnum.parallel]: [
    CHART_TITLE,  CHART_PARALLEL_SERIES, CHART_LEGEND, CHART_X_AXIS, CHART_Y_AXIS, CHART_GRID, CHART_TOOLTIP,
  ],
  [ChartTypesEnum.pictorialBar]: [
    CHART_TITLE,  CHART_PICTORIAL_BAR_SERIES, CHART_LEGEND, CHART_X_AXIS, CHART_Y_AXIS, CHART_GRID, CHART_TOOLTIP,
  ],
  [ChartTypesEnum.sankey]: [
    CHART_TITLE,  CHART_SANKEY_SERIES, CHART_LEGEND, CHART_X_AXIS, CHART_Y_AXIS, CHART_GRID, CHART_TOOLTIP,
  ],
  [ChartTypesEnum.sunburst]: [
    CHART_TITLE,  CHART_SUNBURST_SERIES, CHART_LEGEND, CHART_X_AXIS, CHART_Y_AXIS, CHART_GRID, CHART_TOOLTIP,
  ],
  [ChartTypesEnum.themeRiver]: [
    CHART_TITLE,  CHART_THEME_RIVER_SERIES, CHART_LEGEND, CHART_X_AXIS, CHART_Y_AXIS, CHART_GRID, CHART_TOOLTIP,
  ],
  [ChartTypesEnum.tree]: [
    CHART_TITLE,  CHART_TREE_SERIES, CHART_LEGEND, CHART_X_AXIS, CHART_Y_AXIS, CHART_GRID, CHART_TOOLTIP,
  ],
  [ChartTypesEnum.treemap]: [
    CHART_TITLE,  CHART_TREEMAP_SERIES, CHART_LEGEND, CHART_X_AXIS, CHART_Y_AXIS, CHART_GRID, CHART_TOOLTIP,
  ],
};
