import { ControlTypesEnum } from '../enums';
import {
	CONTROL_BASIC_FIELDS,
	CONTROL_DATEPICKER_FIELDS,
	CONTROL_INPUT_FIELDS,
	CONTROL_LABEL_FIELDS,
	CONTROL_MULTISELECT_FIELDS,
	CONTROL_SELECT_FIELDS,
	CONTROL_DATETIME_FIELDS_DISPLAY,
	CONTROL_DATETIME_FIELDS_DATE,
	CONTROL_DATETIME_FIELDS_TIME,
	CONTROL_DATETIME_FIELDS_FORMAT,
	CONTROL_DATETIME_FIELDS_UPDATE_TZ,
	CONTROL_DATETIME_FIELDS_STYLES,
} from './fields';
import { SafeAny } from '../types';

export const CONTROL_COMPONENT_FIELDS: Partial<Record<ControlTypesEnum, SafeAny>> = {
	[ControlTypesEnum.datePick]: [CONTROL_BASIC_FIELDS, CONTROL_LABEL_FIELDS, CONTROL_DATEPICKER_FIELDS],
	[ControlTypesEnum.select]: [CONTROL_BASIC_FIELDS, CONTROL_LABEL_FIELDS, CONTROL_SELECT_FIELDS],
	[ControlTypesEnum.multiSelect]: [CONTROL_BASIC_FIELDS, CONTROL_LABEL_FIELDS, CONTROL_MULTISELECT_FIELDS],
	[ControlTypesEnum.input]: [CONTROL_BASIC_FIELDS, CONTROL_LABEL_FIELDS, CONTROL_INPUT_FIELDS],
	[ControlTypesEnum.dateTime]: [
		CONTROL_BASIC_FIELDS,
		CONTROL_DATETIME_FIELDS_DISPLAY,
		CONTROL_DATETIME_FIELDS_DATE,
		CONTROL_DATETIME_FIELDS_TIME,
		CONTROL_DATETIME_FIELDS_FORMAT,
		CONTROL_DATETIME_FIELDS_UPDATE_TZ,
		CONTROL_DATETIME_FIELDS_STYLES,
	],
};
