import { ControlTypesEnum } from '../enums';
import { ControlConfig } from '../interfaces';

export const CONTROL_MOCK_DATA: Partial<{ [key in ControlTypesEnum]: ControlConfig }> = {
	[ControlTypesEnum.datePick]: {
		controlId: '',
		controlType: ControlTypesEnum.datePick,
		isActive: true,
		alias: '时间选择器',
		props: {
			selectionMode: 'range',
			dateFormat: 'yy-mm-dd',
			placeholder: '请选择日期',
			showButtonBar: false,
			size: `normal`,
			minDate: null,
			maxDate: null,
		},
		label: {
			enable: true,
			text: '时间',
			description: '这是一个时间标签',
			styles: {
				width: 80,
			},
		},
		bindField: 'testField',
		defaultValue: null,
	},
	[ControlTypesEnum.select]: {
		controlId: '',
		controlType: ControlTypesEnum.select,
		isActive: true,
		alias: '下拉选择器',
		props: {
			placeholder: '请选择',
			showClear: false,
			filter: false,
			filterPlaceholder: '搜索选项',
			disabled: false,
			options: [],
			optionLabel: 'label',
			optionValue: 'value',
		},
		label: {
			enable: true,
			text: '单选',
			description: '这是一个单选标签',
			styles: {
				width: 80,
			},
		},
		bindField: 'testSelectField',
		defaultValue: null,
	},
	[ControlTypesEnum.multiSelect]: {
		controlId: '',
		controlType: ControlTypesEnum.multiSelect,
		isActive: true,
		alias: '多选下拉器',
		props: {
			placeholder: '请选择',
			showClear: false,
			filter: false,
			filterPlaceholder: '搜索选项',
			display: 'comma',
			maxSelectedLabels: 3,
			disabled: false,
			options: [],
			optionLabel: 'label',
			optionValue: 'value',
			showToggleAll: true,
		},
		label: {
			enable: true,
			text: '多选',
			description: '这是一个多选标签',
			styles: {
				width: 80,
			},
		},
		bindField: 'testMultiSelectField',
		defaultValue: [],
	},
	[ControlTypesEnum.input]: {
		controlId: '',
		controlType: ControlTypesEnum.input,
		isActive: true,
		alias: '输入框',
		props: {
			placeholder: '请输入内容',
		},
		label: {
			enable: true,
			text: '输入框',
			description: '这是一个输入框',
			styles: {
				width: 80,
			},
		},
		bindField: 'testInput',
		defaultValue: null,
	},
	[ControlTypesEnum.dateTime]: {
		controlId: '',
		controlType: ControlTypesEnum.dateTime,
		isActive: true,
		alias: '时间',
		props: {
			year: { twoDigits: false, prefix: '', suffix: '' },
			month: { mode: 'number', padZero: true, english: 'long' },
			day: { padZero: true, suffix: '' },
			weekday: { show: false, lang: 'zh', zhStyle: '星期', enStyle: 'long', numberStyle: 'mon-1-7' },
			hourCycle: 24,
			hour: { padZero: true },
			minute: { show: true, padZero: true },
			second: { show: true, padZero: true },
			dateSeparator: '-',
			timeSeparator: ':',
			useChineseDate: false,
			useChineseTime: false,
			customFormat: undefined,
			autoUpdate: { enabled: true, intervalSeconds: 1 },
			updateOnLoad: true,
			timezone: { mode: 'local', offsetMinutes: 0 },
			show: { date: true, time: true, weekday: false },
			order: 'date-time',
			layout: 'single',
			styles: {
				color: undefined,
				fontSize: 13,
				fontWeight: 'normal',
				fontFamily: undefined,
				textAlign: 'left',
				backgroundColor: undefined,
				borderWidth: 0,
				borderColor: undefined,
				borderStyle: 'solid',
				borderRadius: undefined,
				padding: undefined
			}
		}
	},
};
