import { EditorTableField } from '../interfaces';
import {
	ENABLE_OPTIONS,
	GROUP_DISPLAY_TYPE_OPTIONS,
	IS_OPTIONS,
	ROW_GROUP_PANEL_OPTIONS,
	PIVOTING_PANEL_OPTIONS,
	TABLE_SIDE_BAR_OPTIONS,
	YES_OR_NO_OPTIONS,
	AGG_FUNC_OPTIONS,
} from './select-options.const';

// 行分组表格列配置
export const TABLE_COLUMN_DEF: EditorTableField = {
	label: '表格列配置',
	key: 'columnDefs',
	path: 'columnDefs',
	schemaType: 'group',
	headerSetting: [
		{
			field: 'field',
			headerName: '映射字段',
			schemaType: 'text',
		},
		{
			field: 'headerName',
			headerName: '表头名称',
			schemaType: 'text',
		},
		{
			field: 'rowGroup',
			headerName: '分组',
			schemaType: 'select',
			options: ENABLE_OPTIONS,
		},
		{
			field: 'enableRowGroup',
			headerName: '拖拽分组',
			schemaType: 'select',
			options: ENABLE_OPTIONS,
		},
		{
			field: 'pivot',
			headerName: '数据透视',
			schemaType: 'select',
			options: ENABLE_OPTIONS,
		},
		{
			field: 'enablePivot',
			headerName: '拖拽透视',
			schemaType: 'select',
			options: ENABLE_OPTIONS,
		},
		// aggFunc 聚合函数
		{
			field: 'aggFunc',
			headerName: '聚合函数',
			schemaType: 'select',
			clearable: true,
			options: AGG_FUNC_OPTIONS,
		},
		{
			field: 'hide',
			headerName: '隐藏',
			schemaType: 'select',
			options: YES_OR_NO_OPTIONS,
		},
	],
	rowData: [],
};

// 数据透视表
export const TABLE_PIVOTING_COLUMN_DEF: EditorTableField = {
	label: '表格列配置',
	key: 'columnDefs',
	path: 'columnDefs',
	schemaType: 'group',
	headerSetting: [
		{
			field: 'field',
			headerName: '映射字段',
			schemaType: 'text',
		},
		{
			field: 'headerName',
			headerName: '表头名称',
			schemaType: 'text',
		},
		{
			field: 'rowGroup',
			headerName: '启用分组',
			schemaType: 'select',
			options: ENABLE_OPTIONS,
		},
		{
			field: 'enableRowGroup',
			headerName: '拖拽分组',
			schemaType: 'select',
			options: ENABLE_OPTIONS,
		},
		{
			field: 'pivot',
			headerName: '数据透视',
			schemaType: 'select',
			options: ENABLE_OPTIONS,
		},
		{
			field: 'enablePivot',
			headerName: '拖拽透视',
			schemaType: 'select',
			options: ENABLE_OPTIONS,
		},
		{
			field: 'aggFunc',
			headerName: '聚合函数',
			schemaType: 'select',
			clearable: true,
			options: AGG_FUNC_OPTIONS,
		},
		{
			field: 'hide',
			headerName: '隐藏',
			schemaType: 'select',
			options: YES_OR_NO_OPTIONS,
		},
	],
	rowData: [],
};

// 行分组表格默认列设置
export const TABLE_DEFAULT_COL_DEF: EditorTableField = {
	label: '通用列设置',
	key: 'defaultColDef',
	path: 'defaultColDef',
	schemaType: 'group',
	children: [
		{
			label: '栅格占位',
			key: 'flex',
			path: 'defaultColDef.flex',
			schemaType: 'number',
			min: 1,
			max: 100,
			step: 1,
		},
		{
			label: '最小宽度',
			key: 'minWidth',
			path: 'defaultColDef.minWidth',
			schemaType: 'number',
			min: 1,
			max: 9999,
			step: 1,
		},
		{
			label: '启用筛选器',
			key: 'filter',
			path: 'defaultColDef.filter',
			schemaType: 'select',
			description: '当启动数据透视时此功能失效',
			options: ENABLE_OPTIONS,
		},
		{
			label: '启用浮动筛选器',
			key: 'floatingFilter',
			path: 'defaultColDef.floatingFilter',
			schemaType: 'select',
			description: '当启动数据透视时此功能失效',
			options: ENABLE_OPTIONS,
		},
	],
};

// 面板配置
export const TABLE_ROW_GROUPING_PANEL_DEF: EditorTableField = {
	label: '面板配置',
	key: '',
	path: '',
	schemaType: 'group',
	children: [
		{
			label: '数据透视模式',
			key: 'pivotMode',
			path: 'pivotMode',
			schemaType: 'select',
			description: '数据透视模式必要条件:\n 1.至少有一个分组项;\n 2.至少有一组数据启用透视;\n 3.至少有一组数据配置聚合函数.',
			options: ENABLE_OPTIONS,
		},
		{
			label: '数据透视面板展示',
			description: '只有当启用至少一个数据透视时才会生效',
			key: 'pivotPanelShow',
			path: 'pivotPanelShow',
			schemaType: 'select',
			options: PIVOTING_PANEL_OPTIONS,
		},
		{
			label: '行面板展示',
			description: '只有当列分组后才会生效',
			key: 'rowGroupPanelShow',
			path: 'rowGroupPanelShow',
			schemaType: 'select',
			options: ROW_GROUP_PANEL_OPTIONS,
		},
		{
			label: '分组默认展开',
			key: 'groupDefaultExpanded',
			path: 'groupDefaultExpanded',
			schemaType: 'select',
			options: IS_OPTIONS,
		},
		{
			label: '显示父组值',
			key: 'showOpenedGroup',
			path: 'showOpenedGroup',
			schemaType: 'select',
			options: IS_OPTIONS,
		},
		{
			label: '分组样式',
			key: 'groupDisplayType',
			path: 'groupDisplayType',
			schemaType: 'select',
			options: GROUP_DISPLAY_TYPE_OPTIONS,
		},
	],
};

// 数据透视面板配置
export const TABLE_PIVOTING_PANEL_DEF: EditorTableField = {
	label: '面板配置',
	key: '',
	path: '',
	schemaType: 'group',
	children: [
		{
			label: '数据透视面板展示',
			description: '只有当列分组后才会生效',
			key: 'pivotPanelShow',
			path: 'pivotPanelShow',
			schemaType: 'select',
			options: PIVOTING_PANEL_OPTIONS,
		},
		// pivotMode: true,
	],
};

// 侧栏设置
export const TABLE_SIDE_BAR_DEF: EditorTableField = {
	label: '侧边栏设置',
	key: '',
	path: '',
	schemaType: 'group',
	children: [
		{
			label: '侧边栏',
			// description: '选择【过滤器侧栏】时，请在【通用列设置】中启用【筛选器】',
			key: 'sideBar',
			path: 'sideBar',
			schemaType: 'select',
			options: TABLE_SIDE_BAR_OPTIONS,
		},
	],
};

// 数据源配置
export const TABLE_DATA: EditorTableField = {
	label: '数据源设置',
	key: 'data',
	path: 'data',
	schemaType: 'table',
	children: [
		{
			label: '数据源设置',
			key: 'data',
			path: 'data',
			schemaType: 'button',
		},
	],
};

// 样式设置
export const AG_GRID_STYLE_FIELDS: EditorTableField = {
	label: '表格样式配置',
	key: 'tableStyles',
	path: 'tableStyles',
	schemaType: 'group',
	children: [
		// 整体背景样式
		{ label: 'Grid背景色', key: 'agGridBgColor', path: 'tableStyles.agGridBgColor', schemaType: 'color' },
		{
			label: 'Grid背景透明度',
			key: 'agGridBgColorAlpha',
			path: 'tableStyles.agGridBgColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{ label: 'Grid边框色', key: 'agGridBorderColor', path: 'tableStyles.agGridBorderColor', schemaType: 'color' },
		{
			label: 'Grid边框透明度',
			key: 'agGridBorderColorAlpha',
			path: 'tableStyles.agGridBorderColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{ label: 'Grid文字色', key: 'agGridTextColor', path: 'tableStyles.agGridTextColor', schemaType: 'color' },
		{
			label: 'Grid文字透明度',
			key: 'agGridTextColorAlpha',
			path: 'tableStyles.agGridTextColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},

		// 表头样式
		{ label: '表头背景色', key: 'agGridHeaderBgColor', path: 'tableStyles.agGridHeaderBgColor', schemaType: 'color' },
		{
			label: '表头背景透明度',
			key: 'agGridHeaderBgColorAlpha',
			path: 'tableStyles.agGridHeaderBgColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{ label: '表头文字色', key: 'agGridHeaderTextColor', path: 'tableStyles.agGridHeaderTextColor', schemaType: 'color' },
		{
			label: '表头文字透明度',
			key: 'agGridHeaderTextColorAlpha',
			path: 'tableStyles.agGridHeaderTextColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{ label: '表头边框色', key: 'agGridHeaderBorderColor', path: 'tableStyles.agGridHeaderBorderColor', schemaType: 'color' },
		{
			label: '表头边框透明度',
			key: 'agGridHeaderBorderColorAlpha',
			path: 'tableStyles.agGridHeaderBorderColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{ label: '表头悬停色', key: 'agGridHeaderHoverColor', path: 'tableStyles.agGridHeaderHoverColor', schemaType: 'color' },
		{
			label: '表头悬停透明度',
			key: 'agGridHeaderHoverColorAlpha',
			path: 'tableStyles.agGridHeaderHoverColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},

		// 表格行样式
		{ label: '行背景色', key: 'agGridRowBgColor', path: 'tableStyles.agGridRowBgColor', schemaType: 'color' },
		{
			label: '行背景透明度',
			key: 'agGridRowBgColorAlpha',
			path: 'tableStyles.agGridRowBgColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{ label: '行文字色', key: 'agGridRowTextColor', path: 'tableStyles.agGridRowTextColor', schemaType: 'color' },
		{
			label: '行文字透明度',
			key: 'agGridRowTextColorAlpha',
			path: 'tableStyles.agGridRowTextColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{ label: '行边框色', key: 'agGridRowBorderColor', path: 'tableStyles.agGridRowBorderColor', schemaType: 'color' },
		{
			label: '行边框透明度',
			key: 'agGridRowBorderColorAlpha',
			path: 'tableStyles.agGridRowBorderColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{ label: '行悬停色', key: 'agGridRowHoverColor', path: 'tableStyles.agGridRowHoverColor', schemaType: 'color' },
		{
			label: '行悬停透明度',
			key: 'agGridRowHoverColorAlpha',
			path: 'tableStyles.agGridRowHoverColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{ label: '行选中色', key: 'agGridRowSelectedColor', path: 'tableStyles.agGridRowSelectedColor', schemaType: 'color' },
		{
			label: '行选中透明度',
			key: 'agGridRowSelectedColorAlpha',
			path: 'tableStyles.agGridRowSelectedColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},

		// 单元格样式
		{ label: '单元格背景色', key: 'agGridCellBgColor', path: 'tableStyles.agGridCellBgColor', schemaType: 'color' },
		{
			label: '单元格背景透明度',
			key: 'agGridCellBgColorAlpha',
			path: 'tableStyles.agGridCellBgColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{ label: '单元格边框色', key: 'agGridCellBorderColor', path: 'tableStyles.agGridCellBorderColor', schemaType: 'color' },
		{
			label: '单元格边框透明度',
			key: 'agGridCellBorderColorAlpha',
			path: 'tableStyles.agGridCellBorderColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{ label: '单元格焦点色', key: 'agGridCellFocusColor', path: 'tableStyles.agGridCellFocusColor', schemaType: 'color' },
		{
			label: '单元格焦点透明度',
			key: 'agGridCellFocusColorAlpha',
			path: 'tableStyles.agGridCellFocusColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},

		// 侧边栏样式
		{ label: '侧边栏背景色', key: 'agGridSidebarBgColor', path: 'tableStyles.agGridSidebarBgColor', schemaType: 'color' },
		{
			label: '侧边栏背景透明度',
			key: 'agGridSidebarBgColorAlpha',
			path: 'tableStyles.agGridSidebarBgColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{ label: '侧边栏文字色', key: 'agGridSidebarTextColor', path: 'tableStyles.agGridSidebarTextColor', schemaType: 'color' },
		{
			label: '侧边栏文字透明度',
			key: 'agGridSidebarTextColorAlpha',
			path: 'tableStyles.agGridSidebarTextColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{ label: '侧边栏边框色', key: 'agGridSidebarBorderColor', path: 'tableStyles.agGridSidebarBorderColor', schemaType: 'color' },
		{
			label: '侧边栏边框透明度',
			key: 'agGridSidebarBorderColorAlpha',
			path: 'tableStyles.agGridSidebarBorderColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{ label: '侧边栏按钮背景色', key: 'agGridSidebarButtonBgColor', path: 'tableStyles.agGridSidebarButtonBgColor', schemaType: 'color' },
		{
			label: '侧边栏按钮背景透明度',
			key: 'agGridSidebarButtonBgColorAlpha',
			path: 'tableStyles.agGridSidebarButtonBgColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{
			label: '侧边栏按钮悬停色',
			key: 'agGridSidebarButtonHoverColor',
			path: 'tableStyles.agGridSidebarButtonHoverColor',
			schemaType: 'color',
		},
		{
			label: '侧边栏按钮悬停透明度',
			key: 'agGridSidebarButtonHoverColorAlpha',
			path: 'tableStyles.agGridSidebarButtonHoverColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{
			label: '侧边栏按钮选中色',
			key: 'agGridSidebarButtonSelectedColor',
			path: 'tableStyles.agGridSidebarButtonSelectedColor',
			schemaType: 'color',
		},
		{
			label: '侧边栏按钮选中透明度',
			key: 'agGridSidebarButtonSelectedColorAlpha',
			path: 'tableStyles.agGridSidebarButtonSelectedColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},

		// 工具面板样式
		{ label: '工具面板背景色', key: 'agGridToolPanelBgColor', path: 'tableStyles.agGridToolPanelBgColor', schemaType: 'color' },
		{
			label: '工具面板背景透明度',
			key: 'agGridToolPanelBgColorAlpha',
			path: 'tableStyles.agGridToolPanelBgColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{ label: '工具面板文字色', key: 'agGridToolPanelTextColor', path: 'tableStyles.agGridToolPanelTextColor', schemaType: 'color' },
		{
			label: '工具面板文字透明度',
			key: 'agGridToolPanelTextColorAlpha',
			path: 'tableStyles.agGridToolPanelTextColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{
			label: '工具面板头部背景色',
			key: 'agGridToolPanelHeaderBgColor',
			path: 'tableStyles.agGridToolPanelHeaderBgColor',
			schemaType: 'color',
		},
		{
			label: '工具面板头部背景透明度',
			key: 'agGridToolPanelHeaderBgColorAlpha',
			path: 'tableStyles.agGridToolPanelHeaderBgColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{
			label: '工具面板头部边框色',
			key: 'agGridToolPanelHeaderBorderColor',
			path: 'tableStyles.agGridToolPanelHeaderBorderColor',
			schemaType: 'color',
		},
		{
			label: '工具面板头部边框透明度',
			key: 'agGridToolPanelHeaderBorderColorAlpha',
			path: 'tableStyles.agGridToolPanelHeaderBorderColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},

		// 分组面板样式
		{ label: '分组面板背景色', key: 'agGridGroupPanelBgColor', path: 'tableStyles.agGridGroupPanelBgColor', schemaType: 'color' },
		{
			label: '分组面板背景透明度',
			key: 'agGridGroupPanelBgColorAlpha',
			path: 'tableStyles.agGridGroupPanelBgColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{ label: '分组面板文字色', key: 'agGridGroupPanelTextColor', path: 'tableStyles.agGridGroupPanelTextColor', schemaType: 'color' },
		{
			label: '分组面板文字透明度',
			key: 'agGridGroupPanelTextColorAlpha',
			path: 'tableStyles.agGridGroupPanelTextColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{
			label: '分组面板头部背景色',
			key: 'agGridGroupPanelHeaderBgColor',
			path: 'tableStyles.agGridGroupPanelHeaderBgColor',
			schemaType: 'color',
		},
		{
			label: '分组面板头部背景透明度',
			key: 'agGridGroupPanelHeaderBgColorAlpha',
			path: 'tableStyles.agGridGroupPanelHeaderBgColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{
			label: '分组面板头部边框色',
			key: 'agGridGroupPanelHeaderBorderColor',
			path: 'tableStyles.agGridGroupPanelHeaderBorderColor',
			schemaType: 'color',
		},
		{
			label: '分组面板头部边框透明度',
			key: 'agGridGroupPanelHeaderBorderColorAlpha',
			path: 'tableStyles.agGridGroupPanelHeaderBorderColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},

		// 透视面板样式
		{ label: '透视面板背景色', key: 'agGridPivotPanelBgColor', path: 'tableStyles.agGridPivotPanelBgColor', schemaType: 'color' },
		{
			label: '透视面板背景透明度',
			key: 'agGridPivotPanelBgColorAlpha',
			path: 'tableStyles.agGridPivotPanelBgColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{ label: '透视面板文字色', key: 'agGridPivotPanelTextColor', path: 'tableStyles.agGridPivotPanelTextColor', schemaType: 'color' },
		{
			label: '透视面板文字透明度',
			key: 'agGridPivotPanelTextColorAlpha',
			path: 'tableStyles.agGridPivotPanelTextColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{
			label: '透视面板头部背景色',
			key: 'agGridPivotPanelHeaderBgColor',
			path: 'tableStyles.agGridPivotPanelHeaderBgColor',
			schemaType: 'color',
		},
		{
			label: '透视面板头部背景透明度',
			key: 'agGridPivotPanelHeaderBgColorAlpha',
			path: 'tableStyles.agGridPivotPanelHeaderBgColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{
			label: '透视面板头部边框色',
			key: 'agGridPivotPanelHeaderBorderColor',
			path: 'tableStyles.agGridPivotPanelHeaderBorderColor',
			schemaType: 'color',
		},
		{
			label: '透视面板头部边框透明度',
			key: 'agGridPivotPanelHeaderBorderColorAlpha',
			path: 'tableStyles.agGridPivotPanelHeaderBorderColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},

		// 滚动条样式
		{ label: '滚动条轨道色', key: 'agGridScrollbarTrackColor', path: 'tableStyles.agGridScrollbarTrackColor', schemaType: 'color' },
		{
			label: '滚动条轨道透明度',
			key: 'agGridScrollbarTrackColorAlpha',
			path: 'tableStyles.agGridScrollbarTrackColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{ label: '滚动条滑块色', key: 'agGridScrollbarThumbColor', path: 'tableStyles.agGridScrollbarThumbColor', schemaType: 'color' },
		{
			label: '滚动条滑块透明度',
			key: 'agGridScrollbarThumbColorAlpha',
			path: 'tableStyles.agGridScrollbarThumbColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{
			label: '滚动条滑块悬停色',
			key: 'agGridScrollbarThumbHoverColor',
			path: 'tableStyles.agGridScrollbarThumbHoverColor',
			schemaType: 'color',
		},
		{
			label: '滚动条滑块悬停透明度',
			key: 'agGridScrollbarThumbHoverColorAlpha',
			path: 'tableStyles.agGridScrollbarThumbHoverColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},

		// 菜单和弹出框样式
		{ label: '菜单背景色', key: 'agGridMenuBgColor', path: 'tableStyles.agGridMenuBgColor', schemaType: 'color' },
		{
			label: '菜单背景透明度',
			key: 'agGridMenuBgColorAlpha',
			path: 'tableStyles.agGridMenuBgColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{ label: '菜单文字色', key: 'agGridMenuTextColor', path: 'tableStyles.agGridMenuTextColor', schemaType: 'color' },
		{
			label: '菜单文字透明度',
			key: 'agGridMenuTextColorAlpha',
			path: 'tableStyles.agGridMenuTextColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{ label: '菜单边框色', key: 'agGridMenuBorderColor', path: 'tableStyles.agGridMenuBorderColor', schemaType: 'color' },
		{
			label: '菜单边框透明度',
			key: 'agGridMenuBorderColorAlpha',
			path: 'tableStyles.agGridMenuBorderColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{ label: '菜单悬停色', key: 'agGridMenuHoverColor', path: 'tableStyles.agGridMenuHoverColor', schemaType: 'color' },
		{
			label: '菜单悬停透明度',
			key: 'agGridMenuHoverColorAlpha',
			path: 'tableStyles.agGridMenuHoverColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},

		// 筛选器样式
		{ label: '筛选器背景色', key: 'agGridFilterBgColor', path: 'tableStyles.agGridFilterBgColor', schemaType: 'color' },
		{
			label: '筛选器背景透明度',
			key: 'agGridFilterBgColorAlpha',
			path: 'tableStyles.agGridFilterBgColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{ label: '筛选器文字色', key: 'agGridFilterTextColor', path: 'tableStyles.agGridFilterTextColor', schemaType: 'color' },
		{
			label: '筛选器文字透明度',
			key: 'agGridFilterTextColorAlpha',
			path: 'tableStyles.agGridFilterTextColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{ label: '筛选器边框色', key: 'agGridFilterBorderColor', path: 'tableStyles.agGridFilterBorderColor', schemaType: 'color' },
		{
			label: '筛选器边框透明度',
			key: 'agGridFilterBorderColorAlpha',
			path: 'tableStyles.agGridFilterBorderColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{ label: '筛选器头部背景色', key: 'agGridFilterHeaderBgColor', path: 'tableStyles.agGridFilterHeaderBgColor', schemaType: 'color' },
		{
			label: '筛选器头部背景透明度',
			key: 'agGridFilterHeaderBgColorAlpha',
			path: 'tableStyles.agGridFilterHeaderBgColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},

		// 输入框和按钮样式
		{ label: '输入框背景色', key: 'agGridInputBgColor', path: 'tableStyles.agGridInputBgColor', schemaType: 'color' },
		{
			label: '输入框背景透明度',
			key: 'agGridInputBgColorAlpha',
			path: 'tableStyles.agGridInputBgColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{ label: '输入框文字色', key: 'agGridInputTextColor', path: 'tableStyles.agGridInputTextColor', schemaType: 'color' },
		{
			label: '输入框文字透明度',
			key: 'agGridInputTextColorAlpha',
			path: 'tableStyles.agGridInputTextColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{ label: '输入框边框色', key: 'agGridInputBorderColor', path: 'tableStyles.agGridInputBorderColor', schemaType: 'color' },
		{
			label: '输入框边框透明度',
			key: 'agGridInputBorderColorAlpha',
			path: 'tableStyles.agGridInputBorderColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{ label: '输入框焦点色', key: 'agGridInputFocusColor', path: 'tableStyles.agGridInputFocusColor', schemaType: 'color' },
		{
			label: '输入框焦点透明度',
			key: 'agGridInputFocusColorAlpha',
			path: 'tableStyles.agGridInputFocusColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{ label: '按钮背景色', key: 'agGridButtonBgColor', path: 'tableStyles.agGridButtonBgColor', schemaType: 'color' },
		{
			label: '按钮背景透明度',
			key: 'agGridButtonBgColorAlpha',
			path: 'tableStyles.agGridButtonBgColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{ label: '按钮文字色', key: 'agGridButtonTextColor', path: 'tableStyles.agGridButtonTextColor', schemaType: 'color' },
		{
			label: '按钮文字透明度',
			key: 'agGridButtonTextColorAlpha',
			path: 'tableStyles.agGridButtonTextColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{ label: '按钮边框色', key: 'agGridButtonBorderColor', path: 'tableStyles.agGridButtonBorderColor', schemaType: 'color' },
		{
			label: '按钮边框透明度',
			key: 'agGridButtonBorderColorAlpha',
			path: 'tableStyles.agGridButtonBorderColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{ label: '按钮悬停色', key: 'agGridButtonHoverColor', path: 'tableStyles.agGridButtonHoverColor', schemaType: 'color' },
		{
			label: '按钮悬停透明度',
			key: 'agGridButtonHoverColorAlpha',
			path: 'tableStyles.agGridButtonHoverColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},

		// 其他样式
		{ label: '覆盖层背景色', key: 'agGridOverlayBgColor', path: 'tableStyles.agGridOverlayBgColor', schemaType: 'color' },
		{
			label: '覆盖层背景透明度',
			key: 'agGridOverlayBgColorAlpha',
			path: 'tableStyles.agGridOverlayBgColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{ label: '覆盖层文字色', key: 'agGridOverlayTextColor', path: 'tableStyles.agGridOverlayTextColor', schemaType: 'color' },
		{
			label: '覆盖层文字透明度',
			key: 'agGridOverlayTextColorAlpha',
			path: 'tableStyles.agGridOverlayTextColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
		{ label: '调整大小手柄色', key: 'agGridResizeHandleColor', path: 'tableStyles.agGridResizeHandleColor', schemaType: 'color' },
		{
			label: '调整大小手柄透明度',
			key: 'agGridResizeHandleColorAlpha',
			path: 'tableStyles.agGridResizeHandleColorAlpha',
			schemaType: 'number',
			step: 0.1,
			min: 0,
			max: 1,
		},
	],
};
