
// MultiSelect 组件属性配置
import { EditorBaseField, ENABLE_OPTIONS } from 'ngx-puzzle/core';

export const CONTROL_MULTISELECT_FIELDS: EditorBaseField = {
  label: '控件属性',
  key: 'props',
  path: 'props',
  schemaType: 'group',
  children: [
    {
      label: '占位符',
      key: 'placeholder',
      path: 'props.placeholder',
      schemaType: 'text',
      defaultValue: '请选择',
    },
    {
      label: '显示清除按钮',
      key: 'showClear',
      path: 'props.showClear',
      schemaType: 'select',
      defaultValue: false,
      options: ENABLE_OPTIONS,
    },
    {
      label: '可过滤',
      key: 'filter',
      path: 'props.filter',
      schemaType: 'select',
      defaultValue: false,
      options: ENABLE_OPTIONS,
    },
    {
      label: '过滤占位符',
      key: 'filterPlaceholder',
      path: 'props.filterPlaceholder',
      schemaType: 'text',
      defaultValue: '搜索选项',
    },
    {
      label: '显示方式',
      key: 'display',
      path: 'props.display',
      schemaType: 'select',
      defaultValue: 'comma',
      options: [
        { label: '逗号分隔', val: 'comma' },
        { label: '标签显示', val: 'chip' },
      ],
    },
    {
      label: '最大显示标签数',
      key: 'maxSelectedLabels',
      path: 'props.maxSelectedLabels',
      schemaType: 'number',
      min: 1,
      max: 10,
      step: 1,
      defaultValue: 3,
    },
    {
      label: '禁用状态',
      key: 'disabled',
      path: 'props.disabled',
      schemaType: 'select',
      defaultValue: false,
      options: ENABLE_OPTIONS,
    },
    {
      label: '选项标签字段',
      key: 'optionLabel',
      path: 'props.optionLabel',
      schemaType: 'text',
      defaultValue: 'label',
    },
    {
      label: '选项值字段',
      key: 'optionValue',
      path: 'props.optionValue',
      schemaType: 'text',
      defaultValue: 'value',
    },
    {
      label: '关闭图标',
      key: 'showToggleAll',
      path: 'props.showToggleAll',
      schemaType: 'select',
      defaultValue: true,
      options: ENABLE_OPTIONS,
    },
    {
      label: '选项',
      key: 'propsOptions',
      path: 'props.options',
      schemaType: 'options-editor',
      defaultValue: [],
    },
  ],
};
