import { EditorChartField, ENABLE_OPTIONS, FONT_WEIGHT_OPTIONS } from 'ngx-puzzle/core';

// 图例设置 - 基于 ECharts v6 LegendOption 接口
export const CHART_LEGEND: EditorChartField = {
  label: '图例设置',
  key: 'legend',
  schemaType: 'group',
  children: [
    {
      label: '显示图例',
      key: 'legendShow',
      path: 'legend.show',
      schemaType: 'select',
      options: ENABLE_OPTIONS,
      defaultValue: true,
    },
    {
      label: '布局方向',
      key: 'legendOrient',
      path: 'legend.orient',
      schemaType: 'select',
      options: [
        { label: '水平', val: 'horizontal' },
        { label: '垂直', val: 'vertical' }
      ],
      defaultValue: 'horizontal',
    },
    {
      label: '对齐方式',
      key: 'legendAlign',
      path: 'legend.align',
      schemaType: 'select',
      options: [
        { label: '自动', val: 'auto' },
        { label: '左对齐', val: 'left' },
        { label: '右对齐', val: 'right' }
      ],
      defaultValue: 'auto',
    },
    {
      label: '水平位置',
      key: 'legendLeft',
      path: 'legend.left',
      schemaType: 'select',
      options: [
        { label: '左侧', val: 'left' },
        { label: '居中', val: 'center' },
        { label: '右侧', val: 'right' },
        { label: '自定义', val: 'auto' }
      ],
      defaultValue: 'center',
    },
    {
      label: '垂直位置',
      key: 'legendTop',
      path: 'legend.top',
      schemaType: 'select',
      options: [
        { label: '顶部', val: 'top' },
        { label: '中间', val: 'middle' },
        { label: '底部', val: 'bottom' },
        { label: '自定义', val: 'auto' }
      ],
      defaultValue: 'top',
    },
    {
      label: '右侧距离',
      key: 'legendRight',
      path: 'legend.right',
      schemaType: 'number',
      min: 0,
      step: 1,
      description: '距离右侧的像素值',
      defaultValue: null,
    },
    {
      label: '底部距离',
      key: 'legendBottom',
      path: 'legend.bottom',
      schemaType: 'number',
      min: 0,
      step: 1,
      description: '距离底部的像素值',
      defaultValue: null,
    },
    {
      label: '图例宽度',
      key: 'legendWidth',
      path: 'legend.width',
      schemaType: 'number',
      min: 0,
      step: 1,
      description: '图例组件的宽度',
      defaultValue: null,
    },
    {
      label: '图例高度',
      key: 'legendHeight',
      path: 'legend.height',
      schemaType: 'number',
      min: 0,
      step: 1,
      description: '图例组件的高度',
      defaultValue: null,
    },
    {
      label: '背景颜色',
      key: 'legendBackgroundColor',
      path: 'legend.backgroundColor',
      schemaType: 'color',
      defaultValue: 'transparent',
    },
    {
      label: '边框颜色',
      key: 'legendBorderColor',
      path: 'legend.borderColor',
      schemaType: 'color',
      defaultValue: '#ccc',
    },
    {
      label: '边框宽度',
      key: 'legendBorderWidth',
      path: 'legend.borderWidth',
      schemaType: 'number',
      min: 0,
      step: 1,
      defaultValue: 0,
    },
    {
      label: '边框圆角',
      key: 'legendBorderRadius',
      path: 'legend.borderRadius',
      schemaType: 'number',
      min: 0,
      step: 1,
      description: '背景边框的圆角半径',
      defaultValue: 0,
    },
    {
      label: '内边距',
      key: 'legendPadding',
      path: 'legend.padding',
      schemaType: 'number',
      min: 0,
      step: 1,
      description: '图例内边距，也可设置为数组 [上, 右, 下, 左]',
      defaultValue: 5,
    },
    {
      label: '图例项间距',
      key: 'legendItemGap',
      path: 'legend.itemGap',
      schemaType: 'number',
      min: 0,
      step: 1,
      description: '各个图例项之间的间距',
      defaultValue: 10,
    },
    {
      label: '图例标记宽度',
      key: 'legendItemWidth',
      path: 'legend.itemWidth',
      schemaType: 'number',
      min: 0,
      step: 1,
      description: '图例标记的图形宽度',
      defaultValue: 25,
    },
    {
      label: '图例标记高度',
      key: 'legendItemHeight',
      path: 'legend.itemHeight',
      schemaType: 'number',
      min: 0,
      step: 1,
      description: '图例标记的图形高度',
      defaultValue: 14,
    },
    {
      label: '选择模式',
      key: 'legendSelectedMode',
      path: 'legend.selectedMode',
      schemaType: 'select',
      options: [
        { label: '禁用选择', val: false },
        { label: '允许选择', val: true },
        { label: '单选', val: 'single' },
        { label: '多选', val: 'multiple' }
      ],
      defaultValue: true,
      description: '图例选择的模式',
    },
    {
      label: '显示选择器',
      key: 'legendSelector',
      path: 'legend.selector',
      schemaType: 'select',
      options: [
        { label: '不显示', val: false },
        { label: '显示', val: true }
      ],
      defaultValue: false,
      description: '是否显示全选/反选按钮',
    },
    {
      label: '选择器位置',
      key: 'legendSelectorPosition',
      path: 'legend.selectorPosition',
      schemaType: 'select',
      options: [
        { label: '自动', val: 'auto' },
        { label: '开始', val: 'start' },
        { label: '结束', val: 'end' }
      ],
      defaultValue: 'auto',
      description: '选择器按钮的位置',
    },
    {
      label: '选择器按钮间距',
      key: 'legendSelectorItemGap',
      path: 'legend.selectorItemGap',
      schemaType: 'number',
      min: 0,
      step: 1,
      description: '选择器按钮之间的间距',
      defaultValue: 7,
    },
    {
      label: '选择器与图例间距',
      key: 'legendSelectorButtonGap',
      path: 'legend.selectorButtonGap',
      schemaType: 'number',
      min: 0,
      step: 1,
      description: '选择器按钮组与图例项之间的间距',
      defaultValue: 10,
    },
    {
      label: '阴影模糊大小',
      key: 'legendShadowBlur',
      path: 'legend.shadowBlur',
      schemaType: 'number',
      min: 0,
      step: 1,
      defaultValue: 0,
    },
    {
      label: '阴影颜色',
      key: 'legendShadowColor',
      path: 'legend.shadowColor',
      schemaType: 'color',
      defaultValue: 'transparent',
    },
    {
      label: '阴影水平偏移',
      key: 'legendShadowOffsetX',
      path: 'legend.shadowOffsetX',
      schemaType: 'number',
      step: 1,
      defaultValue: 0,
    },
    {
      label: '阴影垂直偏移',
      key: 'legendShadowOffsetY',
      path: 'legend.shadowOffsetY',
      schemaType: 'number',
      step: 1,
      defaultValue: 0,
    },
    {
      label: '触发事件',
      key: 'legendTriggerEvent',
      path: 'legend.triggerEvent',
      schemaType: 'select',
      options: ENABLE_OPTIONS,
      description: '是否触发鼠标或触摸事件',
      defaultValue: false,
    },
    // 图例文字样式设置
    {
      label: '图例文字颜色',
      key: 'legendTextStyleColor',
      path: 'legend.textStyle.color',
      schemaType: 'color',
      defaultValue: '#333',
    },
    {
      label: '图例文字大小',
      key: 'legendTextStyleFontSize',
      path: 'legend.textStyle.fontSize',
      schemaType: 'number',
      min: 8,
      max: 100,
      step: 1,
      defaultValue: 12,
    },
    {
      label: '图例文字粗细',
      key: 'legendTextStyleFontWeight',
      path: 'legend.textStyle.fontWeight',
      schemaType: 'select',
      options: FONT_WEIGHT_OPTIONS,
      defaultValue: 'normal',
    },
    {
      label: '图例文字样式',
      key: 'legendTextStyleFontStyle',
      path: 'legend.textStyle.fontStyle',
      schemaType: 'select',
      options: [
        { label: '正常', val: 'normal' },
        { label: '斜体', val: 'italic' },
        { label: '倾斜', val: 'oblique' }
      ],
      defaultValue: 'normal',
    },
    {
      label: '图例文字字体',
      key: 'legendTextStyleFontFamily',
      path: 'legend.textStyle.fontFamily',
      schemaType: 'text',
      description: '字体系列，如 "Microsoft YaHei", Arial, sans-serif',
      defaultValue: 'sans-serif',
    },
    {
      label: '图例文字行高',
      key: 'legendTextStyleLineHeight',
      path: 'legend.textStyle.lineHeight',
      schemaType: 'number',
      min: 0,
      step: 0.1,
      defaultValue: null,
    },
    {
      label: '图例文字宽度',
      key: 'legendTextStyleWidth',
      path: 'legend.textStyle.width',
      schemaType: 'number',
      min: 0,
      step: 1,
      defaultValue: null,
    },
    {
      label: '图例文字高度',
      key: 'legendTextStyleHeight',
      path: 'legend.textStyle.height',
      schemaType: 'number',
      min: 0,
      step: 1,
      defaultValue: null,
    },
    {
      label: '图例文字描边颜色',
      key: 'legendTextStyleTextBorderColor',
      path: 'legend.textStyle.textBorderColor',
      schemaType: 'color',
      defaultValue: 'transparent',
    },
    {
      label: '图例文字描边宽度',
      key: 'legendTextStyleTextBorderWidth',
      path: 'legend.textStyle.textBorderWidth',
      schemaType: 'number',
      min: 0,
      step: 0.5,
      defaultValue: 0,
    },
    {
      label: '图例文字描边类型',
      key: 'legendTextStyleTextBorderType',
      path: 'legend.textStyle.textBorderType',
      schemaType: 'select',
      options: [
        { label: '实线', val: 'solid' },
        { label: '虚线', val: 'dashed' },
        { label: '点线', val: 'dotted' }
      ],
      defaultValue: 'solid',
    },
    {
      label: '图例文字阴影颜色',
      key: 'legendTextStyleTextShadowColor',
      path: 'legend.textStyle.textShadowColor',
      schemaType: 'color',
      defaultValue: 'transparent',
    },
    {
      label: '图例文字阴影模糊',
      key: 'legendTextStyleTextShadowBlur',
      path: 'legend.textStyle.textShadowBlur',
      schemaType: 'number',
      min: 0,
      step: 1,
      defaultValue: 0,
    },
    {
      label: '图例文字阴影偏移X',
      key: 'legendTextStyleTextShadowOffsetX',
      path: 'legend.textStyle.textShadowOffsetX',
      schemaType: 'number',
      step: 1,
      defaultValue: 0,
    },
    {
      label: '图例文字阴影偏移Y',
      key: 'legendTextStyleTextShadowOffsetY',
      path: 'legend.textStyle.textShadowOffsetY',
      schemaType: 'number',
      step: 1,
      defaultValue: 0,
    },
    // 选择器标签样式设置
    {
      label: '选择器文字颜色',
      key: 'legendSelectorLabelColor',
      path: 'legend.selectorLabel.color',
      schemaType: 'color',
      defaultValue: '#666',
    },
    {
      label: '选择器文字大小',
      key: 'legendSelectorLabelFontSize',
      path: 'legend.selectorLabel.fontSize',
      schemaType: 'number',
      min: 8,
      max: 100,
      step: 1,
      defaultValue: 12,
    },
    {
      label: '选择器文字粗细',
      key: 'legendSelectorLabelFontWeight',
      path: 'legend.selectorLabel.fontWeight',
      schemaType: 'select',
      options: FONT_WEIGHT_OPTIONS,
      defaultValue: 'normal',
    },
    {
      label: '选择器文字字体',
      key: 'legendSelectorLabelFontFamily',
      path: 'legend.selectorLabel.fontFamily',
      schemaType: 'text',
      description: '选择器按钮的字体系列',
      defaultValue: 'sans-serif',
    },
    // 选择器高亮状态样式
    {
      label: '选择器高亮文字颜色',
      key: 'legendEmphasisSelectorLabelColor',
      path: 'legend.emphasis.selectorLabel.color',
      schemaType: 'color',
      defaultValue: '#333',
    },
    {
      label: '选择器高亮文字大小',
      key: 'legendEmphasisSelectorLabelFontSize',
      path: 'legend.emphasis.selectorLabel.fontSize',
      schemaType: 'number',
      min: 8,
      max: 100,
      step: 1,
      defaultValue: 12,
    },
    {
      label: '选择器高亮文字粗细',
      key: 'legendEmphasisSelectorLabelFontWeight',
      path: 'legend.emphasis.selectorLabel.fontWeight',
      schemaType: 'select',
      options: FONT_WEIGHT_OPTIONS,
      defaultValue: 'bold',
    }
  ],
};
