import { EditorChartField, ENABLE_OPTIONS, FONT_WEIGHT_OPTIONS } from 'ngx-puzzle/core';

export const CHART_X_AXIS: EditorChartField = {
  label: 'X轴设置',
  key: 'xAxis',
  schemaType: 'group',
  children: [
    {
      label: '轴类型',
      key: 'xAxisType',
      path: 'xAxis.type',
      schemaType: 'select',
      options: [
        { label: '数值轴', val: 'value' },
        { label: '类目轴', val: 'category' },
        { label: '时间轴', val: 'time' },
        { label: '对数轴', val: 'log' }
      ],
      defaultValue: 'category',
    },
    {
      label: '显示X轴',
      key: 'xAxisShow',
      path: 'xAxis.show',
      schemaType: 'select',
      options: ENABLE_OPTIONS,
      defaultValue: true,
    },
    {
      label: '反向坐标轴',
      key: 'xAxisInverse',
      path: 'xAxis.inverse',
      schemaType: 'select',
      options: ENABLE_OPTIONS,
      defaultValue: false,
      description: '是否反向坐标轴',
    },
    {
      label: '轴名称',
      key: 'xAxisName',
      path: 'xAxis.name',
      schemaType: 'text',
      defaultValue: '',
      description: '坐标轴名称',
    },
    {
      label: '轴名称位置',
      key: 'xAxisNameLocation',
      path: 'xAxis.nameLocation',
      schemaType: 'select',
      options: [
        { label: '开始', val: 'start' },
        { label: '中间', val: 'middle' },
        { label: '居中', val: 'center' },
        { label: '结束', val: 'end' }
      ],
      defaultValue: 'end',
      description: '坐标轴名称显示位置',
    },
    {
      label: '轴名称旋转角度',
      key: 'xAxisNameRotate',
      path: 'xAxis.nameRotate',
      schemaType: 'number',
      min: -360,
      max: 360,
      step: 1,
      defaultValue: null,
      description: '坐标轴名称旋转角度',
    },
    {
      label: '轴名称间距',
      key: 'xAxisNameGap',
      path: 'xAxis.nameGap',
      schemaType: 'number',
      min: 0,
      step: 1,
      defaultValue: 15,
      description: '坐标轴名称与轴线之间的距离',
    },
    {
      label: '轴名称避让',
      key: 'xAxisNameMoveOverlap',
      path: 'xAxis.nameMoveOverlap',
      schemaType: 'select',
      options: [
        { label: '自动', val: 'auto' },
        { label: '启用', val: true },
        { label: '禁用', val: false }
      ],
      defaultValue: 'auto',
      description: '是否自动移动轴名称避免与标签重叠',
    },
    {
      label: '轴名称截断最大宽度',
      key: 'xAxisNameTruncateMaxWidth',
      path: 'xAxis.nameTruncate.maxWidth',
      schemaType: 'number',
      min: 0,
      step: 1,
      defaultValue: null,
      description: '轴名称截断的最大宽度',
    },
    {
      label: '轴名称截断省略符',
      key: 'xAxisNameTruncateEllipsis',
      path: 'xAxis.nameTruncate.ellipsis',
      schemaType: 'text',
      defaultValue: '...',
      description: '轴名称截断时的省略符号',
    },
    {
      label: '轴名称截断占位符',
      key: 'xAxisNameTruncatePlaceholder',
      path: 'xAxis.nameTruncate.placeholder',
      schemaType: 'text',
      defaultValue: '',
      description: '轴名称截断时的占位符',
    },
    {
      label: '最小值',
      key: 'xAxisMin',
      path: 'xAxis.min',
      schemaType: 'text',
      defaultValue: null,
      description: '坐标轴刻度最小值，支持数字或 "dataMin"',
    },
    {
      label: '最大值',
      key: 'xAxisMax',
      path: 'xAxis.max',
      schemaType: 'text',
      defaultValue: null,
      description: '坐标轴刻度最大值，支持数字或 "dataMax"',
    },
    {
      label: '起始值',
      key: 'xAxisStartValue',
      path: 'xAxis.startValue',
      schemaType: 'number',
      defaultValue: null,
      description: '坐标轴起始值',
    },
    {
      label: '静默模式',
      key: 'xAxisSilent',
      path: 'xAxis.silent',
      schemaType: 'select',
      options: ENABLE_OPTIONS,
      defaultValue: false,
      description: '坐标轴是否是静默的，不响应鼠标事件',
    },
    // 轴名称文字样式
    {
      label: '轴名称文字颜色',
      key: 'xAxisNameTextStyleColor',
      path: 'xAxis.nameTextStyle.color',
      schemaType: 'color',
      defaultValue: '#333',
    },
    {
      label: '轴名称文字大小',
      key: 'xAxisNameTextStyleFontSize',
      path: 'xAxis.nameTextStyle.fontSize',
      schemaType: 'number',
      min: 8,
      max: 100,
      step: 1,
      defaultValue: 12,
    },
    {
      label: '轴名称文字粗细',
      key: 'xAxisNameTextStyleFontWeight',
      path: 'xAxis.nameTextStyle.fontWeight',
      schemaType: 'select',
      options: FONT_WEIGHT_OPTIONS,
      defaultValue: 'normal',
    },
    {
      label: '轴名称文字样式',
      key: 'xAxisNameTextStyleFontStyle',
      path: 'xAxis.nameTextStyle.fontStyle',
      schemaType: 'select',
      options: [
        { label: '正常', val: 'normal' },
        { label: '斜体', val: 'italic' },
        { label: '倾斜', val: 'oblique' }
      ],
      defaultValue: 'normal',
    },
    {
      label: '轴名称字体系列',
      key: 'xAxisNameTextStyleFontFamily',
      path: 'xAxis.nameTextStyle.fontFamily',
      schemaType: 'text',
      defaultValue: 'sans-serif',
    },
    {
      label: '轴名称行高',
      key: 'xAxisNameTextStyleLineHeight',
      path: 'xAxis.nameTextStyle.lineHeight',
      schemaType: 'number',
      min: 0,
      step: 0.1,
      defaultValue: null,
    },
    {
      label: '轴名称描边颜色',
      key: 'xAxisNameTextStyleTextBorderColor',
      path: 'xAxis.nameTextStyle.textBorderColor',
      schemaType: 'color',
      defaultValue: 'transparent',
    },
    {
      label: '轴名称描边宽度',
      key: 'xAxisNameTextStyleTextBorderWidth',
      path: 'xAxis.nameTextStyle.textBorderWidth',
      schemaType: 'number',
      min: 0,
      step: 0.5,
      defaultValue: 0,
    },
    {
      label: '轴名称阴影颜色',
      key: 'xAxisNameTextStyleTextShadowColor',
      path: 'xAxis.nameTextStyle.textShadowColor',
      schemaType: 'color',
      defaultValue: 'transparent',
    },
    {
      label: '轴名称阴影模糊',
      key: 'xAxisNameTextStyleTextShadowBlur',
      path: 'xAxis.nameTextStyle.textShadowBlur',
      schemaType: 'number',
      min: 0,
      step: 1,
      defaultValue: 0,
    },
    {
      label: '轴名称阴影偏移X',
      key: 'xAxisNameTextStyleTextShadowOffsetX',
      path: 'xAxis.nameTextStyle.textShadowOffsetX',
      schemaType: 'number',
      step: 1,
      defaultValue: 0,
    },
    {
      label: '轴名称阴影偏移Y',
      key: 'xAxisNameTextStyleTextShadowOffsetY',
      path: 'xAxis.nameTextStyle.textShadowOffsetY',
      schemaType: 'number',
      step: 1,
      defaultValue: 0,
    },
    // 轴标签样式
    {
      label: '显示轴标签',
      key: 'xAxisAxisLabelShow',
      path: 'xAxis.axisLabel.show',
      schemaType: 'select',
      options: ENABLE_OPTIONS,
      defaultValue: true,
    },
    {
      label: '标签间隔',
      key: 'xAxisAxisLabelInterval',
      path: 'xAxis.axisLabel.interval',
      schemaType: 'number',
      min: 0,
      step: 1,
      defaultValue: 'auto',
      description: '坐标轴刻度标签的显示间隔，0表示显示所有标签',
    },
    {
      label: '标签旋转角度',
      key: 'xAxisAxisLabelRotate',
      path: 'xAxis.axisLabel.rotate',
      schemaType: 'number',
      min: -90,
      max: 90,
      step: 1,
      defaultValue: 0,
    },
    {
      label: '标签内边距',
      key: 'xAxisAxisLabelMargin',
      path: 'xAxis.axisLabel.margin',
      schemaType: 'number',
      min: 0,
      step: 1,
      defaultValue: 8,
      description: '刻度标签与轴线之间的距离',
    },
    {
      label: '标签文字颜色',
      key: 'xAxisAxisLabelColor',
      path: 'xAxis.axisLabel.color',
      schemaType: 'color',
      defaultValue: '#666',
    },
    {
      label: '标签文字大小',
      key: 'xAxisAxisLabelFontSize',
      path: 'xAxis.axisLabel.fontSize',
      schemaType: 'number',
      min: 8,
      max: 100,
      step: 1,
      defaultValue: 12,
    },
    {
      label: '标签文字粗细',
      key: 'xAxisAxisLabelFontWeight',
      path: 'xAxis.axisLabel.fontWeight',
      schemaType: 'select',
      options: FONT_WEIGHT_OPTIONS,
      defaultValue: 'normal',
    },
    {
      label: '标签字体系列',
      key: 'xAxisAxisLabelFontFamily',
      path: 'xAxis.axisLabel.fontFamily',
      schemaType: 'text',
      defaultValue: 'sans-serif',
    },
    // 轴线样式
    {
      label: '显示轴线',
      key: 'xAxisAxisLineShow',
      path: 'xAxis.axisLine.show',
      schemaType: 'select',
      options: ENABLE_OPTIONS,
      defaultValue: true,
    },
    {
      label: '轴线颜色',
      key: 'xAxisAxisLineLineStyleColor',
      path: 'xAxis.axisLine.lineStyle.color',
      schemaType: 'color',
      defaultValue: '#333',
    },
    {
      label: '轴线宽度',
      key: 'xAxisAxisLineLineStyleWidth',
      path: 'xAxis.axisLine.lineStyle.width',
      schemaType: 'number',
      min: 0,
      step: 0.5,
      defaultValue: 1,
    },
    {
      label: '轴线类型',
      key: 'xAxisAxisLineLineStyleType',
      path: 'xAxis.axisLine.lineStyle.type',
      schemaType: 'select',
      options: [
        { label: '实线', val: 'solid' },
        { label: '虚线', val: 'dashed' },
        { label: '点线', val: 'dotted' }
      ],
      defaultValue: 'solid',
    },
    // 轴刻度样式
    {
      label: '显示刻度',
      key: 'xAxisAxisTickShow',
      path: 'xAxis.axisTick.show',
      schemaType: 'select',
      options: ENABLE_OPTIONS,
      defaultValue: true,
    },
    {
      label: '刻度长度',
      key: 'xAxisAxisTickLength',
      path: 'xAxis.axisTick.length',
      schemaType: 'number',
      min: 0,
      step: 1,
      defaultValue: 5,
    },
    {
      label: '刻度线颜色',
      key: 'xAxisAxisTickLineStyleColor',
      path: 'xAxis.axisTick.lineStyle.color',
      schemaType: 'color',
      defaultValue: '#333',
    },
    {
      label: '刻度线宽度',
      key: 'xAxisAxisTickLineStyleWidth',
      path: 'xAxis.axisTick.lineStyle.width',
      schemaType: 'number',
      min: 0,
      step: 0.5,
      defaultValue: 1,
    },
    // 分割线样式
    {
      label: '显示分割线',
      key: 'xAxisSplitLineShow',
      path: 'xAxis.splitLine.show',
      schemaType: 'select',
      options: ENABLE_OPTIONS,
      defaultValue: false,
    },
    {
      label: '分割线颜色',
      key: 'xAxisSplitLineLineStyleColor',
      path: 'xAxis.splitLine.lineStyle.color',
      schemaType: 'color',
      defaultValue: '#ccc',
    },
    {
      label: '分割线宽度',
      key: 'xAxisSplitLineLineStyleWidth',
      path: 'xAxis.splitLine.lineStyle.width',
      schemaType: 'number',
      min: 0,
      step: 0.5,
      defaultValue: 1,
    },
    {
      label: '分割线类型',
      key: 'xAxisSplitLineLineStyleType',
      path: 'xAxis.splitLine.lineStyle.type',
      schemaType: 'select',
      options: [
        { label: '实线', val: 'solid' },
        { label: '虚线', val: 'dashed' },
        { label: '点线', val: 'dotted' }
      ],
      defaultValue: 'solid',
    },
    // 分割区域样式
    {
      label: '显示分割区域',
      key: 'xAxisSplitAreaShow',
      path: 'xAxis.splitArea.show',
      schemaType: 'select',
      options: ENABLE_OPTIONS,
      defaultValue: false,
    }
  ],
};

// ... 现有代码 ...
